version: '3.4'

x-common-config:
  &common-config
  image: "{{ project_name }}:${STOLOS_PUBLIC_URL}"
  env_file:
    - environments/stolos.env
  volumes:
    - ${STOLOS_REMOTE_DIR}/{{ project_name }}:/usr/src/app/{{ project_name }}
    - ${STOLOS_REMOTE_DIR}/users:/usr/src/app/users
  networks:
    - intelligems-central

x-common-environment:
  &common-environment
  SWARM_MODE: "False"
  DEBUG: "True"
  DATABASE_URL: ${DATABASE_URL}
  ALLOWED_HOSTS: ${STOLOS_PUBLIC_URL}
  REDIS_URL: redis://redis-central:6379
  MEMCACHED_URL: memcached-central
  LOGGING_LEVEL: INFO

networks:
  intelligems-central:
    external:
      name: intelligems-central

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: EXPERIMENTAL
    command: python manage.py runserver 0.0.0.0:8000
#    For debug uncomment below
#    command: python manage.py runserver 0.0.0.0:8000 --pdb
#    stdin_open: true
#    tty: true
    << : *common-config
    environment:
      << : *common-environment
      RUN_MIGRATIONS: "1"
    ports:
      - 8000

  worker:
    command: celery -A {{ project_name }} worker -l info
    << : *common-config
    environment:
      << : *common-environment
      RUN_MIGRATIONS: "0"
      C_FORCE_ROOT: "true"
    depends_on:
      - web

  beat:
    command: celery -A {{ project_name }} beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    << : *common-config
    environment:
      << : *common-environment
      RUN_MIGRATIONS: "0"
      C_FORCE_ROOT: "true"
    depends_on:
      - web

  flower:
    command: celery flower -A {{ project_name }} -l info --address=0.0.0.0 --port=5555 --persistent
    << : *common-config
    environment:
      << : *common-environment
      RUN_MIGRATIONS: "0"
      C_FORCE_ROOT: "true"
    depends_on:
      - web
    ports:
      - 5555
