version: '3.4'

services:
  pgadmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "/mnt/efs/pgadmin:/var/lib/pgadmin"